services:
  db:
    image: postgres:16
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yeework
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

  backend:
    container_name: backend
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    volumes:
      - upload_folder:/app/uploads
      - logs:/app/logs
    networks:
      - app-network

  ui:
    restart: always
    depends_on:
      - backend
    container_name: ui
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ui
    networks:
      - app-network

  nginx:
    restart: always
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - ui
    networks:
      - app-network
    volumes:
      - upload_folder:/usr/local/uploads

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  upload_folder:
  logs:
