services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    networks:
      - app-network

  ui:
    restart: always
    depends_on:
      - backend
    container_name: ui
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ui
    networks:
      - app-network

  nginx:
    restart: always
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - ui
    networks:
      - app-network

networks:
  app-network:
    driver: bridge