[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["Boris <boris.lok.tw@outlook.com>"]

[lib]
name = "backend"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
async-trait = "0.1.81"
anyhow = "1.0.86"
ulid = "1.1.3"
axum = { version = "0.7.5", features = ["multipart"] }
axum-macros = "0.4.1"
axum-extra = "0.9.3"
config = "0.14.0"
tokio = { version = "1.39.3", features = ["full"] }
thiserror = "1.0.63"
tower = "0.5.0"
tower-http = { version = "0.6.1", features = ["cors"] }
sqlx = { version = "0.8.2", features = ["chrono", "macros", "migrate", "postgres", "runtime-tokio-rustls"] }
chrono = { version = "0.4.38", default-features = false, features = ["serde"] }
image = "0.25.2"
validator = { version = "0.18.1", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v4"] }
secrecy = { version = "0.10.3", features = ["serde"] }
argon2 = { version = "0.5.3", features = ["std"] }
rand = "0.8.5"
