[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["Boris <boris.lok.tw@outlook.com>"]

[lib]
name = "backend"
path = "src/lib.rs"

[[bin]]
name = "generate_sitemap"
path = "src/bin/generate_sitemap.rs"

[[bin]]
name = "create_user"
path = "src/bin/create_user.rs"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
async-trait = "0.1.89"
anyhow = "1.0.102"
ulid = "1.2.1"
axum = { version = "0.8.8", features = ["multipart"] }
axum-macros = "0.5.0"
axum-extra = { version = "0.12.5", features = ["typed-header", "with-rejection"] }
config = "0.15.19"
tokio = { version = "1.49.0", features = ["full"] }
thiserror = "2.0.18"
tower = "0.5.3"
tower-http = { version = "0.6.8", features = ["cors", "set-header"] }
sqlx = { version = "0.8.6", features = ["chrono", "macros", "migrate", "postgres", "runtime-tokio-rustls", "uuid", "ipnet"] }
chrono = { version = "0.4.43", default-features = false, features = ["serde"] }
image = "0.25.9"
validator = { version = "0.20.0", features = ["derive"] }
uuid = { version = "1.21.0", features = ["v4"] }
secrecy = { version = "0.10.3", features = ["serde"] }
argon2 = { version = "0.5.3", features = ["std"] }
rand = "0.10.0"
jsonwebtoken = "10.3.0"
redis = { version = "1.0.4", features = ["tokio-comp"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["json"] }
tracing-log = "0.2.0"
