[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["Boris <boris.lok.tw@outlook.com>"]

[lib]
name = "backend"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
async-trait = "0.1.81"
anyhow = "1.0.86"
