database:
  host: 127.0.0.1
  # if we dockerized the application, we need to change the host to the database service name
  # host: db
  port: 15432
  username: postgres
  password: yeework
  database_name: db
  require_ssl: false
  timeout: 5
application:
  port: 8081
  host: 127.0.0.1
  upload_folder: /Users/boris/Documents/workspace/projects/attorneys-website/upload/
  log_file: /Users/boris/Documents/workspace/projects/attorneys-website/logs/log.txt
  jwt_secret: secret
redis_uri: redis://127.0.0.1:6379
