database:
  host: 127.0.0.1
  # if we dockerized the application, we need to change the host to the database service name
  # host: db
  port: 15432
  username: postgres
  password: yeework
  database_name: db
  require_ssl: false
  timeout: 5
