# Step 1: Build the Svelte application
# Create a builder
from node:22 as builder

# Setup the working directory
workdir /app

# Install app dependencies using pnpm
# run npm install -g pnpm

## Copy the rest of the application code
copy ../ui/ .
## Replace the .env to production environment
copy ../ui/.env ./.env

## Delete the node_modules and previous build files
run rm -rf /app/node_modules
run rm -rf /app/.svelte-kit

run npm cache clean --force
run npm install --verbose

run npm run build

expose 3000

## Run command
cmd ["node", "build"]
